### PR TITLE
update dependencies, add scripts

### PR DESCRIPTION
**Pull request by milahu**
**update dependencies**

eslint-config-airbnb-base requires eslint@^7.2.0

typescript is reported as missing peer dep by pnpm

**add scripts**

prepare script is needed to install from git

before

```
pnpm i -g https://github.com/futurGH/ts-to-jsdoc
ts-to-jsdoc
Error: Cannot find module './ts-to-jsdoc.js'
```

after

```
pnpm rm -g ts-to-jsdoc
pnpm i -g github:futurGH/ts-to-jsdoc#pull/11/merge
ts-to-jsdoc

Usage:
  ts-to-jsdoc [options] <path>...
```

**also transform d.ts files to d.js**

example input, based on
https://github.com/GoogleChromeLabs/browser-fs-access/blob/main/index.d.ts

index.d.ts

```ts
/**
 * Whether the File System Access API is supported.
 */
export const supported: boolean;

export function imageToBlob(img: HTMLImageElement): Promise<Blob>;

export interface FileWithHandle extends File {
  handle?: FileSystemFileHandle;
}
```

example output

index.d.js

```js
/**
 * Whether the File System Access API is supported.
 * @type {boolean}
 */
export const supported = (() => {
    throw new Error("FIXME this is a variable signature from a *.d.ts declaration file. please move this to the *.js implementation file");
})();
/** @param {HTMLImageElement} img
 * @returns {Promise<Blob>}
 */
export function imageToBlob(img) {
    throw new Error("FIXME this is a function signature from a *.d.ts declaration file. please move this to the *.js implementation file");
}




/** @typedef {Object} FileWithHandle
 * @property {FileSystemFileHandle} [handle] 
 */
```

future work:
move types to the *.js implementation files
there, import needed types with
`/** @typedef {import("../index.d.js").SomeType} SomeType */`

**fixes and features**

i needed to transform this d.ts file
https://github.com/GoogleChromeLabs/browser-fs-access/blob/main/index.d.ts
so this mostly works now

future work: fix function types

example: legacySetup

expected: keep whitespace

```js
/**
 * The first `options` object passed to file save operations can also specify
 * a filename
 * @typedef {Object} FirstFileSaveOptions
 * @property {string} [fileName] Suggested file name. Defaults to `"Untitled"`.
 * @property {(
 *   resolve: () => void,
 *   rejectionHandler: () => void,
 *   anchor: HTMLAnchorElement
 * ) => () => void} [legacySetup] 
```

actual: whitespace is lost

```js
/**
 * The first `options` object passed to file save operations can also specify
 * a filename
 * @typedef {Object} FirstFileSaveOptions
 * @property {string} [fileName] Suggested file name. Defaults to `"Untitled"`.
 * @property {(resolve:()=>void,rejectionHandler:()=>void,anchor:HTMLAnchorElement)=>()=>void} [legacySetup] 
```

### CODE REVIEW

**Comment by futurGH** [comment]
Thanks for the contribution! Is `.d.js` a common format/convention? What tools use it? This is my first time seeing it referenced and I'm not sure how much utility it adds to support something like that.

**Comment by milahu** [comment]
> Is `.d.js` a common format/convention? What tools use it?

its non-standard

my goal is to move all types to jsdoc types
and then generate a *.d.ts file from jsdoc types

jsconfig.json

```json5
{
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "target": "esnext",
    "jsx": "react",
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "checkJs": true,
    // produce index.d.ts file
    "declaration": true,
    "emitDeclarationOnly": true,
    "noEmit": true,
  },
  "exclude": [
    "node_modules",
    "**/node_modules/*",
  ]
}
```

*.d.js can be used in jsdoc imports in the the implementation *.js files

```js
/** @typedef {import("../index.d.js").SomeType} SomeType */
```

currently *.d.js has these error messages

> FIXME this is a variable signature from a *.d.ts declaration file. please move this to the *.js implementation file

> FIXME this is a function signature from a *.d.ts declaration file. please move this to the *.js implementation file

ideally, we transform a whole typescript project with multiple source files
so we can move function signatures and variable signatures to the *.js implementation files

... and maybe declare shared types in types.js
types.js has only `@typedef` jsdoc comments, no js code
example: https://github.com/eslint/eslint/blob/main/lib/shared/types.js

**Comment by futurGH** [comment]
Gotcha, thanks for explaining. I feel I might need to be clearer on what ts-to-jsdoc is/isn't. For any given TS code, its output should, at runtime, behave identically; this is a goal shared with TypeScript proper, just because I feel introducing code with runtime effects (e.g. `.d.ts` -> `.d.js`) could open the door to significant scope creep beyond what I envisioned for this package.

I can definitely see the utility in something like `.d.js` as a consistent standard for JSDoc typedefs, I just think it would be better suited to being a separate package.

I would, however, appreciate the JSDoc generation improvements and package.json changes as a standalone PR :-)

**Comment by milahu** [comment]
> I would, however, appreciate the JSDoc generation improvements and package.json changes as a standalone PR :-)

feel free to cherry-pick the bugfix in https://github.com/futurGH/ts-to-jsdoc/pull/11/commits/83ab1a243dca8899d226a8f9ed327db215669f2a
the bug shows only for array.length > 1

also https://github.com/futurGH/ts-to-jsdoc/pull/11/commits/72025bbd5086fb3ec03683c711267dad7857d10b is useful to install ts-to-jsdoc from git

the gist of https://github.com/futurGH/ts-to-jsdoc/pull/11/commits/f3a05b91d9ad00fce67fe9af44f710cb6c960bc6 is to show a better error message

```diff
-		console.error(error(`Could not transpile ${filepath}.`));
+		console.error(error(`Nothing was replaced in ${filepath}.`));
```

... this was an internal error.
when the filename ends with .d.ts then typescript emits nothing.
to transform *.d.ts files, i rename them to ${base}.ts-to-jsdoc.ts

all other commits are for transforming *.d.ts files, or trivial stuff

> it would be better suited to being a separate package

true ... could be named reverse-dts, or dts2jsdoc

i still owe you an explanation of my use case
i want to transform a d.ts file to jsdoc types
https://github.com/jimmywarting/native-file-system-adapter/issues/24#issuecomment-1326807881

source: https://github.com/GoogleChromeLabs/browser-fs-access/blob/main/index.d.ts

```ts
/**
 * Opens a directory from disk using the File System Access API.
 * @returns Contained files.
 */
export function directoryOpen(options?: {
  /** Whether to recursively get subdirectories. */
  recursive: boolean;
  /** Suggested directory in which the file picker opens. */
  startIn?: WellKnownDirectory | FileSystemHandle;
  /** By specifying an ID, the user agent can remember different directories for different IDs. */
  id?: string;
  /** By specifying a mode of `'readwrite'`, you can open a directory with write access. */
  mode?: FileSystemPermissionMode;
```

target: https://github.com/jimmywarting/native-file-system-adapter/blob/master/src/showDirectoryPicker.js

```js
/**
 * @param {Object} [options]
 * @param {boolean} [options._preferPolyfill] If you rather want to use the polyfill instead of the native
 * @returns {Promise<FileSystemDirectoryHandle>}
 */
async function showDirectoryPicker (options = {}) {
  if (native && !options._preferPolyfill) {
    return native(options)
  }
```

note: for showDirectoryPicker, the options type is incomplete
its missing options.recursive options.startIn options.id options.mode ...

in this case, an automatic transform is not possible
because different names: directoryOpen != showDirectoryPicker

so, i need the function signature of `directoryOpen` with jsdoc types
and copy it manually to `showDirectoryPicker`
= semi-automatic migration, still better than manual migration

in this case, i cannot use the implementation types
https://github.com/GoogleChromeLabs/browser-fs-access/blob/main/src/fs-access/directory-open.mjs

```js
/**
 * Opens a directory from disk using the File System Access API.
 * @type { typeof import("../index").directoryOpen }
 */
export default async (options = {}) => {
```

because `import("../index")` resolves to the `index.d.ts` file

**Pull request closed without merging**
