### PR TITLE
add namespace generation

### LINKED ISSUE #48: Question about namespaces for ts-to-jsdoc
Hey again, 

I have a few projects that use namespaces in JSDoc. Are you open to the idea of generating namespaces in JSDoc?

For example:

```typescript
/** Namespace description */
export namespace Example {
  /** Type description */
  export type SubType = {
    /** Property description */
    name: string
  }

  /** Interface description */
  export interface SubInterface {
    /** Property description */
    label: string;
  }
}
```

would become:

```javascript
/**
 * Namespace description
 * @namespace Example
 */
/**
 * Type description
 * @typedef {Object} Example.SubType
 * @property {string} name Property description
 */
/**
 * Interface description
 * @typedef {Object} Example.SubInterface
 * @property {string} label Property description
 */
```

### PR DESCRIPTION
**Pull request by smacpherson64**
Aims to add namespace jsdoc generation to ts-to-jsdoc

Resolves https://github.com/futurGH/ts-to-jsdoc/issues/48

### CODE REVIEW

**Comment by futurGH** [comment]
On a quick initial look, this largely looks good — my only note would be that since a namespace can exist at the value level if it exports any variables or functions, it'd make sense for generateNamespaceDocumentation to prepend the JSDoc to the transpiled namespace if one exists.

**Comment by smacpherson64** [comment]
Understood, great point will think through how to approach.

**Comment by smacpherson64** [comment]
Hey @futurGH,

I updated the functionality, and tests, to handle value and type only namespaces. I am not sure how to fix the spacing issue with the JSDoc on the value version yet. I will try to investigate more when I am able.

**Comment by futurGH** [comment]
Sorry for the wait! Hoping to get around to reviewing this soon.

**Comment by smacpherson64** [comment]
Hey @futurGH, No worries. Please do not feel pressure on my account. Your time is important. Thanks for the update!

**Comment by futurGH** [comment]
Everything looks great, thanks for the contribution!

**Comment by smacpherson64** [comment]
Thanks for being open to the idea and for the feedback!

**Pull request merged**
